baseURL = "https://berfr.me/"
languageCode = "en-us"
title = "berfr blog"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
enableGitInfo = true

pygmentsCodeFences = true
pygmentsUseClasses = true
